Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2018-07, with the labels that each got.

#1 Rewrite imports for the cloud/google code so that it doesn't depend on the vendored code from the cluster-api repository.
  cloud/google/clients/clients_test.go
  cloud/google/clients/cloudbilling_test.go
  cloud/google/clients/cloudresourcemanagerservice_test.go
  cloud/google/clients/computeservice_test.go
  cloud/google/clients/servicemanagement_test.go
  cloud/google/clusteractuator.go
  cloud/google/clusteractuator_test.go
  cloud/google/cmd/gce-controller/Dockerfile
  cloud/google/cmd/gce-controller/cluster-controller-app/controller.go
  cloud/google/cmd/gce-controller/machine-controller-app/controller.go
  cloud/google/cmd/gce-controller/main.go
  cloud/google/gceproviderconfig/v1alpha1/register.go
  cloud/google/machineactuator.go
  cloud/google/machineactuator_test.go
  cloud/google/machinesetup/config_types.go
  cloud/google/machinesetup/config_types_test.go
  cloud/google/metadata.go
  cloud/google/pods.go
  cloud/google/serviceaccount.go
Labels: cncf-cla: yes, size/M

#2 Ignore files created by IntelliJ IDEA / GoLand.
  .gitignore
Labels: cncf-cla: yes, size/XS

#3 Set a PR template to use in this repository
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf-cla: yes, size/S

#5 Change the comment syntax in the boilerplate file.
  boilerplate.go.txt
Labels: cncf-cla: yes, lgtm, size/S

#4 Update dependencies running `dep ensure`.
  Gopkg.lock
Labels: cncf-cla: yes, lgtm, size/S

#6 Add scripts to that we can turn on presubmit checks
  Makefile
  cloud/google/clusteractuator.go
  cmd/gce-controller/.gitignore
  cmd/gce-controller/Dockerfile
  cmd/gce-controller/Makefile
  cmd/gce-controller/README.md
  cmd/gce-controller/cluster-controller-app/controller.go
  cmd/gce-controller/cluster-controller-app/options/options.go
  cmd/gce-controller/machine-controller-app/controller.go
  cmd/gce-controller/machine-controller-app/options/options.go
  cmd/gce-controller/main.go
  cmd/generate-image/main.go
  scripts/ci-build.sh
  scripts/ci-make.sh
  scripts/ci-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#11 Move the script to clean up service accounts into the scripts directory
  README.md
  cloud/google/README.md
  scripts/delete-service-accounts.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#12 Update the cluster-api dependency to get support for cluster deletion
  Gopkg.lock
  vendor/sigs.k8s.io/cluster-api/clusterctl/clusterdeployer/clusterdeployer.go
  vendor/sigs.k8s.io/cluster-api/clusterctl/cmd/create_cluster.go
  vendor/sigs.k8s.io/cluster-api/clusterctl/cmd/delete_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#23 Fix gofmt
  cmd/gce-controller/machine-controller-app/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#24 Exit from main with exit code 1 on error
  cmd/gce-controller/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#22 Add goflag parsing to pflags
  cmd/gce-controller/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#29 Fix glog.Info -> glog.Infof
  cloud/google/machineactuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#30 Don't always log an error message
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#27 Update cluster-api dependency to latest master
  Gopkg.lock
  Gopkg.toml
  vendor/sigs.k8s.io/cluster-api/clusterctl/clusterdeployer/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/clusterctl/clusterdeployer/clusterapiservertemplate.go
  vendor/sigs.k8s.io/cluster-api/clusterctl/clusterdeployer/minikube/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/clusterctl/cmd/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/clusterctl/providercomponents/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/clusterctl/validation/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/common/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/cert/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/scheme/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/client/informers_generated/externalversions/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/client/informers_generated/externalversions/cluster/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/client/informers_generated/externalversions/cluster/v1alpha1/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/client/informers_generated/externalversions/internalinterfaces/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/client/listers_generated/cluster/v1alpha1/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/clientcmd/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/cmd-runner/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/controller/config/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/controller/noderefutil/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/controller/sharedinformers/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/errors/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/kubeadm/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/test-cmd-runner/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/util/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/L

#32 Fix typo: boostrap -> bootstrap
  cloud/google/machineactuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
