Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2018-11, with the labels that each got.

#54 Add support for K8s v1.12, drop support for v1.9
  cmd/clusterctl/examples/google/machine_setup_configs.yaml
  cmd/clusterctl/examples/google/machines.yaml.template
  cmd/clusterctl/examples/google/provider-components.yaml.template
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#56 .gitignore: Add some temp files
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#62 Add -f (--fail) flag to all curl invocations
  Dockerfile
  cmd/clusterctl/examples/google/machine_setup_configs.yaml
  cmd/clusterctl/examples/google/provider-components.yaml.template
  pkg/cloud/google/machineactuator.go
  scripts/fetch_ext_bins.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#63 Dockerfile: move manager from /root/ to /
  Dockerfile
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#65 State explicitly K8s version to be used in bootstrap cluster.
  .gitignore
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
