Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2018-10, with the labels that each got.

#39 Be explicit that minikube <= 0.28.0 is required for now.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#41 Update getting started instructions
  README.md
  cmd/clusterctl/examples/google/addons.yaml.template
  config/rbac/rbac_role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#47 Remove the note about using an old, vulnerable version of minikube.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#43 Remove duplicate boilerplate file.
  boilerplate.go.txt
Labels: approved, cncf-cla: yes, lgtm, size/S

#46 Remove ginkgo / gomega
  Gopkg.toml
  pkg/apis/gceproviderconfig/v1alpha1/gceclusterproviderconfig_types_test.go
  pkg/apis/gceproviderconfig/v1alpha1/gcemachineproviderconfig_types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
