Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2018-12, with the labels that each got.

#67 Allow gcp-provider-manager-role to update Machine status
  config/rbac/rbac_role.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#74 Remove string concatenation in /etc/default
  cmd/clusterctl/examples/google/machine_setup_configs.yaml
  cmd/clusterctl/examples/google/provider-components.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S

#76 Boilerplate & a few typo fixes
  pkg/cloud/google/clients/errors/errors.go
  pkg/cloud/google/clients/token_source.go
  pkg/cloud/google/serviceaccount.go
  pkg/controller/add_cluster.go
  pkg/controller/add_machine.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#78 Fix the name of kustomized files.
  config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#79 Fix log output, now that the cluster-api has switched to klog.
  cmd/clusterctl/main.go
  cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#77 Changes after running make on a clean checkout.
  pkg/cloud/google/machineactuator.go
  vendor/google.golang.org/api/dfareporting/v2.8/dfareporting-api.json
  vendor/google.golang.org/api/dfareporting/v2.8/dfareporting-gen.go
  vendor/google.golang.org/api/prediction/v1.6/prediction-api.json
  vendor/google.golang.org/api/prediction/v1.6/prediction-gen.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
