Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2019-12, with the labels that each got.

#259 🏃Update controller-tools version
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#258 ⚠️ Move Status.APIEndpoints to Spec.ControlPlaneEndpoint
  api/v1alpha3/gcpcluster_types.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  cloud/scope/cluster.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  controllers/gcpcluster_controller.go
  controllers/gcpmachine_controller.go
  controllers/gcpmachine_controller_unit_test.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#261 🐛 make create-cluster: Improve cert-manager wait
  Makefile
  examples/generate.sh
  go.mod
  go.sum
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#263 🐛Update KubeadmConfig(s) to v1alpha3
  examples/controlplane/controlplane.yaml
  examples/controlplane/kustomizeversions.yaml
  examples/machinedeployment/kustomizeversions.yaml
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#265 🏃 Update to KIND v0.6.1
  Makefile
  hack/ensure-kind.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#262 ⚠️Rename ErrorMessage and ErrorReason to FailureMessage and FailureReason
  api/v1alpha3/gcpmachine_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  cloud/scope/machine.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  controllers/gcpmachine_controller.go
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#264 ⚠️ Rename cert-manager API group from certmanager.k8s.io to cert-manager.io
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_gcpclusters.yaml
  config/crd/patches/cainjection_in_gcpmachines.yaml
  config/crd/patches/cainjection_in_gcpmachinetemplates.yaml
  config/default/webhookcainjection_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#269 :running: Remove clusterctl dependency from create-cluster
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#268 :running: Update Go 1.13
  .golangci.yml
  Dockerfile
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
  go.mod
  hack/ensure-go.sh
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
  scripts/ensure-go.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#272 🏃 Let GCB build release images
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#274 :running: Exclude pprof lint warning in golangci-lint config
  .golangci.yml
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#270 :sparkles: Support bootstrap data in secret
  cloud/scope/machine.go
  cloud/services/compute/instances.go
  config/rbac/role.yaml
  controllers/gcpmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#275 Fix conformance tests
  Makefile
  examples/cluster/kustomizeconfig.yaml
  examples/controlplane/kustomizeconfig.yaml
  examples/machinedeployment/kustomizeconfig.yaml
  go.mod
  go.sum
  hack/ci/e2e-conformance.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#276 :sparkles: Add tilt
  .dockerignore
  .gitignore
  tilt-provider.json
Labels: approved, cncf-cla: yes, lgtm, size/S
