Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2019-05, with the labels that each got.

#114 Attempt to patch up docker version and make consistent between ControlPlane and Nodes
  cmd/clusterctl/examples/google/machine_setup_configs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#118 Add default disk
  pkg/cloud/google/machineactuator.go
  pkg/cloud/google/machineactuator_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#120 Strip `v` from `kubelet` and `controlplane` version
  pkg/cloud/google/machineactuator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#123 feat: support additional metadata for instances
  cmd/clusterctl/examples/google/machine_setup_configs.yaml
  pkg/cloud/google/machineactuator_test.go
  pkg/cloud/google/machinesetup/config_types.go
  pkg/cloud/google/machinesetup/config_types_test.go
  pkg/cloud/google/metadata.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#127 Update Readme to include go installation
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
