Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2019-06, with the labels that each got.

#130 Allow specification of subnets & AliasIPRanges
  config/crds/gceproviderconfig_v1alpha1_gcemachineproviderspec.yaml
  pkg/apis/gceproviderconfig/v1alpha1/gcemachineproviderconfig_types.go
  pkg/apis/gceproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/google/machineactuator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#131 Implement UpdateStatus for error reporting
  pkg/cloud/google/machineactuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#139 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S
