Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2019-10, with the labels that each got.

#191 ✨Fix loop for instances when pulling logs
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#193 📖 Fixup README badges links
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#194 🏃Fixup release Makefile targets
  Makefile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#195 Tweak how we get the zone info for an instance
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#196 ⚠️ Allow to specify a custom network in Cluster.Spec
  api/v1alpha2/gcpcluster_types.go
  api/v1alpha2/labels.go
  api/v1alpha2/types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/scope/cluster.go
  cloud/services/compute/firewalls.go
  cloud/services/compute/instancegroup.go
  cloud/services/compute/instances.go
  cloud/services/compute/network.go
  cloud/services/compute/service.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  controllers/gcpcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#198 ✨ Simplify travesing the list of instances
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#199 🏃 Use released components instead of building
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#192 Create a new network for us to use, still allow default to work
  Makefile
  examples/cluster/cluster.yaml
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#200 Fetch more logs - this time from all the GCP nodes
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#201 ✨ Skip cleanup for local development scenario
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#203 ✨Add a way to run master branch of capi and cabpk
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#204 ✨ Make target for updating dependencies
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#205 Option to skip running tests
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#207 ✨Add option to toggle verbosity
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#208 📖Add dev oriented doc for the conformance tests
  docs/conformance.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#206 Add option to cleanup
  docs/conformance.md
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#209 ✨ print version numbers for CAPI and CABPK during generate
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#210 ✨ Log a bunch more diagnostic information
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#211 🐛 Support running alongside other Cluster API pods in the same namespace with leader election enabled
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#212 🏃Verify go mod files and generated files
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#213 hack/ci/e2e-conformance.sh: update the kustomize install path
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, priority/important-soon, size/XS

#216 ✨Update to latest "stable" releases
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#217 ✨Dump info from all the CRDs
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#218 Update kubernetes version to 1.16.1
  examples/generate.sh
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#219 ✨ Support the new --use-ci-artifacts for testing against k/k ci builds
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#220 ✨Clean up bootstrap file
  examples/controlplane/kustomizeversions.yaml
  examples/machinedeployment/kustomizeversions.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#221 Add option to reuse images explicitly
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#222 🏃Add make release-note
  Makefile
  examples/generate.sh
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#215 ✨ Allow the ability to configure frontend and backend port for LB
  api/v1alpha2/types.go
  cloud/scope/cluster.go
  cloud/services/compute/firewalls.go
  cloud/services/compute/instancegroup.go
  cloud/services/compute/loadbalancers.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#223 :warning: Change manager image to release-0.2
  config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#224 Fast forward to v1alpha3 types
  api/v1alpha3/gcpcluster_types.go
  api/v1alpha3/gcpmachine_types.go
  api/v1alpha3/gcpmachinetemplate_types.go
  api/v1alpha3/groupversion_info.go
  api/v1alpha3/labels.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  cloud/scope/cluster.go
  cloud/scope/machine.go
  cloud/services/compute/firewalls.go
  cloud/services/compute/instancegroup.go
  cloud/services/compute/instances.go
  cloud/services/compute/loadbalancers.go
  cloud/services/compute/network.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
  controllers/gcpcluster_controller.go
  controllers/gcpcluster_controller_test.go
  controllers/gcpmachine_annotations.go
  controllers/gcpmachine_controller.go
  controllers/gcpmachine_controller_test.go
  controllers/gcpmachine_controller_unit_test.go
  controllers/suite_test.go
  examples/cluster/cluster.yaml
  examples/controlplane/controlplane.yaml
  examples/generate.sh
  examples/machinedeployment/machinedeployment.yaml
  go.mod
  go.sum
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#225 :bug: Default to master branch in generate.sh
  examples/generate.sh
  examples/provider-components/kustomization.yaml
  examples/provider-components/manager_tolerations_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#226 🏃 Update Go 1.12.10 and modules
  Dockerfile
  config/default/manager_image_patch.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#227 🏃Install kustomize under hack/tools, run make modules before build
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#230 Automated cherry pick of #227: Install kustomize under hack/tools, run make modules before
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#231 :bug: Fixup image patch
  config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#229 Automated cherry pick of #226: Update Go 1.12.10 and modules
  Dockerfile
  config/default/manager_image_patch.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#232 :bug: Update Makefile for better ImagePullPolicy defaults
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#233 :bug: Set PULL_POLICY to Never in CI e2e
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#234 :bug: Add clusterName to MD template
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#235 🐛PHASE has upper case letter now - running->Running
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#236 🏃Bump kubernetes version in generated examples to 1.16.2
  examples/generate.sh
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#240 🐛Fix control-plane label to capg-controller-manager
  config/manager/manager.yaml
  config/rbac/auth_proxy_service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#239 🐛Add NETWORK_NAME when generating example manifests
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#241 :sparkles: Add addresses to machine status
  cloud/scope/machine.go
  controllers/gcpmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#242 :sparkles: Add addresses to machine status
  cloud/scope/machine.go
  controllers/gcpmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#244 🐛 Change error message to say gcp/gce instead of ec2
  cloud/services/compute/service.go
  controllers/gcpmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
