Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2019-11, with the labels that each got.

#245 🏃 Replace names with aws to say gcp
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_gcpclusters.yaml
  config/crd/patches/cainjection_in_gcpmachines.yaml
  config/crd/patches/cainjection_in_gcpmachinetemplates.yaml
  config/crd/patches/webhook_in_gcpclusters.yaml
  config/crd/patches/webhook_in_gcpmachines.yaml
  config/crd/patches/webhook_in_gcpmachinetemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#247 ✨ Add printer columns for gcpcluster and gcpmachine
  api/v1alpha3/gcpcluster_types.go
  api/v1alpha3/gcpmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#248 ✨ work with pod utils - fix go/src directory location
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#252 Automated cherry pick of #248: work with pod utils - fix go/src directory location
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#249 ✨Fine tune ci-e2e / e2e-conformance.sh
  hack/ci/e2e-conformance.sh
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#253 generate: don't concat machinedeployment output
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#254 🏃Reduce cleanup timeout
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#257 :bug: Fix conformance tests, install cert-manager
  Makefile
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/S
