Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2019-09, with the labels that each got.

#144 Fixed cluster-api link
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#146 ✨Add prow image push
  Makefile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#148 🐛 fix: remove line breaks in base64 encoding
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#149 :running: Point to correct image in kustomize patch
  config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#145 Follow-up fixes from #143
  api/v1alpha2/gcpcluster_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/services/compute/instances.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
  controllers/gcpcluster_controller.go
  controllers/gcpmachine_controller.go
  go.mod
  go.sum
  main.go
  record/recorder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#158 🐛 fix: fix reading of semver for kube version
  cloud/services/compute/instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#155 ✨ Add the ability to customize Service Account and Scopes
  api/v1alpha2/gcpmachine_types.go
  api/v1alpha2/types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloud/services/compute/instances.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#159 🐛 Fix event recorder name
  cloud/scope/clients.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#160 Avoid hard coding the cluster name in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#161 Reflect current state of slow startup
  examples/controlplane/controlplane.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#119 Add NodeRole if nodeRole not provided
  pkg/cloud/google/machineactuator.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, ok-to-test, size/S

#162 Reconcile Loadbalancers when we update instance group
  controllers/gcpmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#164 Update to newer cluster ctl with better retry handling
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#166 🐛 Fix GCPCluster watcher on GCPMachines / delete instance groups
  cloud/services/compute/instancegroup.go
  cloud/services/compute/loadbalancers.go
  controllers/gcpcluster_controller.go
  controllers/gcpmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#168 🐛 Only watch GCPCluster / reconcile backend services on Machines
  cloud/services/compute/loadbalancers.go
  controllers/gcpcluster_controller.go
  controllers/gcpmachine_controller.go
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#170 🐛 Save self link in ReconcileInstanceGroup
  cloud/services/compute/instancegroup.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#169 🐛 Encoded credentials now works across linux and osx
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#172 🐛 Reconcile instance groups before updating backends
  cloud/services/compute/loadbalancers.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#174 Add CI script for running e2e conformance tests
  hack/checkin_account.py
  hack/checkout_account.py
  hack/ci/README.md
  hack/ci/e2e-conformance.sh
  hack/ensure-kind.sh
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#178 Replace references to AWS
  cloud/services/compute/instances.go
  go.mod
  go.sum
  main.go
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#177 Harden ci scripts and get e2e working
  examples/generate.sh
  hack/checkout_account.py
  hack/ci/e2e-conformance.sh
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#179 Better activity log and don't fail when there are no instances
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#181 Clean up ci job - fix nats cleanup / add boskos heartbeat
  hack/ci/e2e-conformance.sh
  hack/heartbeat_account.py
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#180 :book: Add prerequisites file
  docs/prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#182 Build/Use k8s 1.16.0 image in packer
  hack/ci/e2e-conformance.sh
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#183 add-access-config needs zone info
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#187 ✨ Refactor source image computation
  cloud/services/compute/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#184 ✨ Tweak some descriptions / comments
  api/v1alpha2/gcpmachine_types.go
  cloud/services/compute/instances.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#185 🐛 Don't try to validate disk size updates
  controllers/gcpmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#188 Build/use gcp cluster-api-provider image explicitly
  Makefile
  config/default/manager_image_patch.yaml
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#190 ✨Append to boskos log, no need for nohup
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#189 ✨ Log activity from when we started the job
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
