Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2020-11, with the labels that each got.

#325 🏃 Update worker nodes for conformance test
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#326 Link in makefile has changed
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#327 Update link to image-builder git repo
  docs/prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#328 Fix calling timeout for osx
  Makefile
  docs/prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#322 🏃 update CAPI to v0.3.10
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#332 🏃 fix image-builder rule and Use latest k8s version when using ci artifacts
  docs/prerequisites.md
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#312 ✨[api/gcpmachine] Support root volume type param.
  api/v1alpha3/gcpmachine_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  cloud/services/compute/instances.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#331 [compute/instances]: Fix subnet resource path. 🐛
  cloud/services/compute/instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#329 :running: Add a releasing doc
  docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/M
