Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2020-12, with the labels that each got.

#334 🏃 Add e2e tests using the cluster-api framework
  .dockerignore
  .gitignore
  Makefile
  config/manager/manager.yaml
  config/manager/manager_image_patch.yaml
  config/manager/manager_pull_policy.yaml
  hack/ensure-kind.sh
  hack/ensure-kustomize.sh
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
  templates/test/cluster-template-ci.yaml
  test/e2e/common.go
  test/e2e/config/gcp-ci.yaml
  test/e2e/data/cni/calico/calico.yaml
  test/e2e/e2e_test.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#337 🏃 Proposal: add cpanato to capg maintainers list
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S

#310 ✨ Support FailureDomains override(optional) in GCPClusterSpec
  api/v1alpha3/gcpcluster_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  controllers/gcpcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#307 ✨ Auto create Cloud NAT if network is created by CAPG
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  cloud/services/compute/network.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#338 📖 release: update notes and makefile from feedback of release 0.3.0
  Makefile
  docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#339 docs: update PR template to add kind and release notes section
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#340 capi: update capi to 0.3.11
  Makefile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#341 Update CAPI to v0.3.12
  Makefile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/S
