Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2020-02, with the labels that each got.

#282 :running: Switch Kubernetes CI URL
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#283 :running: [0.2] Switch Kubernetes CI URL
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#284 🐛 fix-failing-test
  examples/controlplane/kustomizeversions.yaml
  examples/machinedeployment/kustomizeversions.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#285 ✨health: Add liveness and readiness probes
  config/manager/manager.yaml
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
