Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2021-06, with the labels that each got.

#363 update CAPI dependency to v0.3.16
  Makefile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, release-note, size/L

#371 capi: update capi to release v0.3.17
  Makefile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S

#370 ci: update k8s cluster to use 1.19.10 version
  hack/ci/e2e-conformance.sh
  scripts/ci-e2e.sh
  test/e2e/config/gcp-ci.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#372 ✨ Add externally managed predicate to GCPCluster controller
  controllers/gcpcluster_controller.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/S

#375 docs/release: update based on the release v0.3.1
  docs/releasing.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#347 check ErrNotFound for delete requests, also remove finalizer if VM not found
  cloud/services/compute/firewalls.go
  cloud/services/compute/instancegroup.go
  cloud/services/compute/instances.go
  cloud/services/compute/loadbalancers.go
  cloud/services/compute/network.go
  cloud/services/compute/service.go
  controllers/gcpmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#374 Update CAPI to v0.4.0-beta.0
  Makefile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#376 capi: using released artifacts from github
  Makefile
  test/e2e/config/gcp-ci.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XS

#378 cloudbuild: increase job timeout
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#379 capg: add initial capi tests
  test/e2e/capi_test.go
  test/e2e/common.go
  test/e2e/config/gcp-ci.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#380 Set default for curl retries
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#381 Update CAPI release to v0.4.0-beta.1
  Makefile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#382 dev-workflow: add tilt and documentation to develop capg
  .gitignore
  Dockerfile
  Makefile
  Tiltfile
  docs/development.md
  hack/ensure-go.sh
  hack/kustomize-sub.sh
  scripts/kind-with-registry.sh
  scripts/setup-dev-enviroment.sh
  tilt_modules/cert_manager/README.md
  tilt_modules/cert_manager/Tiltfile
  tilt_modules/cert_manager/test/Tiltfile
  tilt_modules/cert_manager/test/test.sh
  tilt_modules/extensions.json
Labels: approved, cncf-cla: yes, kind/documentation, kind/feature, lgtm, release-note, size/XL

#384 golangci-lint: update golangci rules and fix the lints
  .golangci.yml
  api/v1alpha3/gcpmachine_types.go
  api/v1alpha3/groupversion_info.go
  api/v1alpha4/gcpcluster_webhook.go
  api/v1alpha4/gcpmachine_types.go
  api/v1alpha4/gcpmachine_webhook.go
  api/v1alpha4/groupversion_info.go
  cloud/gcperrors/errors.go
  cloud/scope/getters.go
  cloud/scope/machine.go
  cloud/services/compute/firewalls.go
  cloud/services/compute/instancegroup.go
  cloud/services/compute/instances.go
  cloud/services/compute/loadbalancers.go
  cloud/services/compute/network.go
  cloud/services/compute/regions.go
  cloud/services/compute/service.go
  cloud/wait/wait.go
  controllers/gcpmachine_controller.go
  controllers/gcpmachine_controller_unit_test.go
  hack/boilerplate/test/fail.go
  util/reconciler/defaults.go
  version/version.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#383 deps: update dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/L

#386 🏃 Fixup README googlecloud icon link
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#385 🏃 Fix compiler UndeclaredName error
  test/e2e/common.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#387 ci: add golangci-lint to run using github-actions
  .github/workflows/lint.yml
  scripts/ci-test.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#390 Fix typos in the development doc
  docs/development.md
Labels: approved, cncf-cla: yes, kind/bug, kind/documentation, lgtm, release-note-none, size/XS

#394 Refactor cloud services into Reconcile/Delete pattern
  cloud/defaults.go
  cloud/doc.go
  cloud/gcperrors/errors.go
  cloud/interfaces.go
  cloud/scope/clients.go
  cloud/scope/cluster.go
  cloud/scope/machine.go
  cloud/services/compute/firewalls.go
  cloud/services/compute/firewalls/doc.go
  cloud/services/compute/firewalls/reconcile.go
  cloud/services/compute/firewalls/service.go
  cloud/services/compute/instancegroup.go
  cloud/services/compute/instances.go
  cloud/services/compute/instances/doc.go
  cloud/services/compute/instances/reconcile.go
  cloud/services/compute/instances/reconcile_test.go
  cloud/services/compute/instances/service.go
  cloud/services/compute/loadbalancers.go
  cloud/services/compute/loadbalancers/doc.go
  cloud/services/compute/loadbalancers/reconcile.go
  cloud/services/compute/loadbalancers/service.go
  cloud/services/compute/network.go
  cloud/services/compute/networks/doc.go
  cloud/services/compute/networks/reconcile.go
  cloud/services/compute/networks/service.go
  cloud/services/compute/regions.go
  cloud/services/compute/service.go
  cloud/wait/wait.go
  controllers/gcpcluster_controller.go
  controllers/gcpcluster_controller_test.go
  controllers/gcpmachine_controller.go
  controllers/gcpmachine_controller_test.go
  controllers/gcpmachine_controller_unit_test.go
  go.mod
  go.sum
  main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XXL
