Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2021-10, with the labels that each got.

#443 Duplicate link checker in the workflow
  .github/workflows/lint-link.yml
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#406 Wait for webhook readiness and healthy
  main.go
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#440 Replace Windows with Windows+WSL2
  docs/book/src/developers/development.md
  docs/book/src/developers/releasing.md
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/S, approved, lgtm, ok-to-test
