Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2021-07, with the labels that each got.

#395 Update CAPI to v0.4.0
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#396 Add pre-requisites for default network setup
  docs/prerequisites.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note, size/M

#399 use dl.k8s.io instead of hardcoded GCS URIs
  Makefile
  hack/ci/e2e-conformance.sh
  hack/ensure-kubectl.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XS

#400 ci: use prebuilt node images for CAPG
  hack/ci/e2e-conformance.sh
  scripts/ci-e2e.sh
  templates/cluster-template.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#398 Use GA TargetTcpProxies after updated upstream
  cloud/scope/clients.go
  cloud/scope/cluster.go
  cloud/services/compute/loadbalancers/reconcile.go
  cloud/services/compute/loadbalancers/service.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#402 GCPClusterTemplate CRD added
  PROJECT
  api/v1alpha4/gcpclustertemplate_types.go
  api/v1alpha4/gcpclustertemplate_webhook.go
  api/v1alpha4/gcpclustertemplate_webhook_test.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_gcpclustertemplates.yaml
  config/crd/patches/webhook_in_gcpclustertemplates.yaml
  config/rbac/gcpclustertemplate_editor_role.yaml
  config/rbac/gcpclustertemplate_viewer_role.yaml
  config/webhook/manifests.yaml
  main.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XL
