Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2021-09, with the labels that each got.

#410 Added quick start section to readme
  README.md
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#411 Added contributing & involvement section
  README.md
Labels: release-note-none, cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#412 Modified the office hours & communication section
  README.md
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#414 Added docs section
  README.md
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#413 Added github issues section
  README.md
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#416 Added support policy to gcp
  README.md
Labels: release-note-none, cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#418 Added flannel.md to the docs
  docs/flannel.md
Labels: release-note, cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#417 Moved docs to book
  docs/README.md
  docs/book/src/developers/development.md
  docs/book/src/developers/releasing.md
  docs/book/src/topics/conformance.md
  docs/book/src/topics/prerequisites.md
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#423 Improvements to contributing.md
  CONTRIBUTING.md
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#427 Update dependencies for v0.4.3
  .github/workflows/lint.yml
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
Labels: release-note, cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#426 Improvement of github workflow and added test coverage
  .github/workflows/cover.yaml
  .github/workflows/lint-link.yml
  .markdownlinkcheck.json
Labels: release-note, cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#429 Update CAPI image path from master->main
  README.md
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/XS, approved, lgtm, ok-to-test

#431 Fixed broken links // prerequisites, development guide
  README.md
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/XS, approved, lgtm, ok-to-test

#437 Correction made in the support policy section
  README.md
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/S, approved, lgtm, ok-to-test
