Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2021-12, with the labels that each got.

#466 Update k8s version to latest 1.22 patch version
  Tiltfile
  docs/book/src/developers/development.md
  docs/book/src/topics/prerequisites.md
  hack/ci/e2e-conformance.sh
  scripts/ci-e2e.sh
  test/e2e/config/gcp-ci.yaml
Labels: release-note, cncf-cla: yes, size/S, approved, lgtm

#474 remove not needed conformance script and update docs
  Makefile
  docs/book/src/topics/conformance.md
  hack/ci/README.md
  hack/ci/e2e-conformance.sh
  scripts/ci-conformance-old.sh
Labels: release-note, cncf-cla: yes, size/XL, approved, lgtm, kind/cleanup

#475 Update capi and project dependencies
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm

#468 Management cluster creation without clusterctl
  docs/book/src/developers/cluster-creation.md
Labels: release-note, cncf-cla: yes, size/M, approved, lgtm

#477 [release-1.0] cherry picks #474 #475
  Makefile
  Tiltfile
  docs/book/src/topics/conformance.md
  go.mod
  go.sum
  hack/ci/README.md
  hack/ci/e2e-conformance.sh
  scripts/ci-conformance-old.sh
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, approved, lgtm, kind/cleanup
