Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2021-11, with the labels that each got.

#457 [api/labels] Initialize nil dest labels during addition.
  api/v1alpha3/labels.go
  api/v1alpha4/labels.go
  api/v1beta1/labels.go
  cloud/services/compute/instances/reconcile_test.go
  go.mod
Labels: kind/bug, release-note, cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#464 Bump golangci-lint to 1.43.0
  .github/workflows/lint.yml
  Makefile
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup

#465 version: fix version in the manager logs
  Dockerfile
  Makefile
  go.mod
  main.go
Labels: kind/bug, release-note-none, cncf-cla: yes, size/S, approved, lgtm, kind/cleanup
