Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2021-04, with the labels that each got.

#357 Bump ginkgo version to v1.15.2
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#358 Update cloudbuild to Go 1.16
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#354 Update klog dependency to v2
  cloud/scope/cluster.go
  cloud/scope/machine.go
  cloud/wait/wait.go
  controllers/gcpmachine_controller_unit_test.go
  controllers/suite_test.go
  go.mod
  main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/S

#362 Option to just build image needed in scripts/ci-e2e.sh
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/S

#364 Add dims as maintainer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#360 dependencies: update several dependencies
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, release-note, size/L

#366 Install go if needed
  hack/ensure-go.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XS
