Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2022-03, with the labels that each got.

#545 enable quiet mode for docs link checker
  .github/workflows/link-check.yml
Labels: kind/feature, release-note, cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#544 Add CAPG label to tilt-provider.json
  tilt-provider.json
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm

#534 add ci-apidiff job along with apidiff target
  Makefile
  scripts/ci-apidiff.sh
Labels: release-note, cncf-cla: yes, size/M, approved, lgtm

#532 owners: cleanup and move members to emeritus
  OWNERS
  OWNERS_ALIASES
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm, kind/cleanup

#528 Verify lint-fix added to Makefile
  Makefile
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm

#548 Cleanup go install script
  scripts/go_install.sh
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm, kind/cleanup

#549 update capi to release v0.4.8
  Tiltfile
  go.mod
  go.sum
  hack/ci/e2e-conformance.sh
  scripts/ci-e2e.sh
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/M, approved, lgtm

#547 Add script to run the test coverage
  Makefile
  scripts/ci-test-coverage.sh
Labels: release-note, cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash

#552 Update CAPI to release v1.0.5
  Makefile
  Tiltfile
  go.mod
  go.sum
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/M, approved, lgtm

#551 Use `git clone` to get source
  docs/book/src/developers/development.md
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/XS, approved, lgtm, kind/cleanup

#553 update CAPI to v1.1.3
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/capi_test.go
  test/e2e/config/gcp-ci.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-upgrades.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/M, approved, lgtm

#539 add verify-tiltfile target
  Makefile
  Tiltfile
  hack/verify-starlark.sh
Labels: release-note, cncf-cla: yes, size/L, approved, lgtm

#557 fix: Install Cert Manager and Documentation
  docs/book/src/developers/development.md
  hack/install-cert-manager.sh
Labels: release-note, cncf-cla: yes, kind/documentation, size/XS, approved, lgtm, kind/cleanup, ok-to-test

#559 Fix v1alpha4 <-> v1beta1 API conversions
  api/v1alpha3/gcpmachinetemplate_conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/conversion_test.go
  api/v1alpha4/gcpclustertemplate_conversion.go
  api/v1alpha4/gcpmachinetemplate_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/gcpclustertemplate_conversion.go
  api/v1beta1/gcpclustertemplate_types.go
  api/v1beta1/gcpclustertemplate_webhook_test.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
Labels: kind/bug, release-note, cncf-cla: yes, size/L, approved, lgtm, kind/failing-test

#571 Bump to golangci-lint v1.45.2
  .github/workflows/lint.yml
  Makefile
Labels: kind/feature, release-note, cncf-cla: yes, size/XS, approved, lgtm

#568 Add ClusterClass quickstart e2e test
  test/e2e/capi_test.go
  test/e2e/config/gcp-ci.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-topology.yaml
  test/e2e/data/infrastructure-gcp/clusterclass-quick-start.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm
