Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2022-02, with the labels that each got.

#500 update capi to release v1.0.4
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/M, approved, lgtm

#497 Align kubectl install and CI scripts to use local bin folder
  Makefile
  hack/install-cert-manager.sh
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
  scripts/kind-with-registry.sh
Labels: release-note, cncf-cla: yes, size/M, approved, lgtm

#507 Replaced `go get` with `go install` to install binaries
  scripts/go_install.sh
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup

#502 [release-1.0][cherry-pick] update capi to release v1.0.4
  Dockerfile
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/ensure-go.sh
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/M, approved, lgtm

#503 [release-0.4] update go to 1.16.13 and capi to v0.4.7
  Dockerfile
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/ensure-go.sh
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/M, approved, lgtm

#506 update CAPI discussion link
  README.md
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm, tide/merge-method-squash, ok-to-test

#501 Bumps Go to 1.17 and CAPI to v1.1.0
  .golangci.yml
  Dockerfile
  Makefile
  Tiltfile
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  docs/book/src/developers/development.md
  go.mod
  go.sum
  hack/ensure-go.sh
  metadata.yaml
  test/e2e/config/gcp-ci.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: release-note, cncf-cla: yes, size/L, approved, lgtm

#513 update k8s version to use 1.22.6 with the new images that is built
  docs/book/src/developers/cluster-creation.md
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
  test/e2e/config/gcp-ci.yaml
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm, kind/cleanup

#508 Use custom service accounts instead of default for controllers
  config/manager/manager.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/S, approved, lgtm

#517 Reflect changes on support policy section
  README.md
Labels: release-note, cncf-cla: yes, kind/documentation, size/S, approved, lgtm

#515 Update controller-runtime, controller-tools, k8s-client and kustomize
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/M, approved, lgtm

#518 e2e/tests: add upgrade k8s tests
  go.mod
  go.sum
  test/e2e/capi_test.go
  test/e2e/config/gcp-ci.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-ci.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-prow-ci-version.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-upgrades.yaml
Labels: release-note, cncf-cla: yes, size/L, approved, lgtm

#519 e2e/upgrade: add HA upgrade tests
  Makefile
  test/e2e/capi_test.go
Labels: kind/feature, release-note, cncf-cla: yes, size/S, approved, lgtm

#499 add dependabot config
  .github/dependabot.yml
Labels: kind/feature, release-note-none, cncf-cla: yes, size/S, approved, lgtm

#520 tests/e2e: add remediation tests
  test/e2e/capi_test.go
  test/e2e/config/gcp-ci.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-md-remediation.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm

#514 Use controller-runtime setup-envtest and generate junit report in ci-test.sh
  Makefile
  scripts/ci-test.sh
  scripts/fetch_ext_bins.sh
Labels: release-note, cncf-cla: yes, size/L, approved, lgtm

#531 cni: update calico to version v3.22 and CAPI to v1.1.2
  Tiltfile
  config/manager/manager.yaml
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
  test/e2e/data/cni/calico/calico.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-prow-ci-version.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm, kind/cleanup

#530 update go to 1.17.7
  Dockerfile
  hack/ensure-go.sh
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup
