Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2022-12, with the labels that each got.

#766 update ginko to v2, CAPI to 1.3.x, go to 1.19 and certmanager to v1.10.0
  Dockerfile
  Makefile
  Tiltfile
  clusterctl-settings.json
  controllers/gcpcluster_controller_test.go
  controllers/gcpmachine_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  hack/install-cert-manager.sh
  hack/tools/go.mod
  metadata.yaml
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
  scripts/go_install.sh
  test/e2e/capi_test.go
  test/e2e/common.go
  test/e2e/config/gcp-ci.yaml
  test/e2e/conformance_test.go
  test/e2e/data/cni/calico/calico.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/e2e_test.go
  test/e2e/suite_test.go
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, approved, lgtm, kind/cleanup

#771 Remove myself from maintainers, update reviewer group
  OWNERS
  OWNERS_ALIASES
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm

#773 update CAPI to v1.3.0 and bump k8s versions and public k8s registry
  Makefile
  Tiltfile
  go.mod
  go.sum
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/M, approved, lgtm

#775 feat: per cluster credentials
  api/v1alpha3/gcpcluster_conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/conversion_test.go
  api/v1alpha4/gcpcluster_conversion.go
  api/v1alpha4/gcpclustertemplate_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/gcpcluster_types.go
  api/v1beta1/gcpcluster_webhook.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/cluster.go
  cloud/services/compute/instances/reconcile_test.go
  cloud/services/compute/subnets/reconcile_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
  controllers/gcpcluster_controller.go
  controllers/gcpmachine_controller.go
  test/e2e/common.go
  test/e2e/config/gcp-ci.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-ci-with-creds.yaml
  test/e2e/e2e_test.go
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm

#778 Fix panic when ClusterNetwork is nil
  cloud/scope/cluster.go
Labels: kind/bug, release-note, cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#777 Add support for shielded instance
  api/v1alpha3/gcpmachine_conversion.go
  api/v1alpha3/gcpmachinetemplate_conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/gcpmachine_conversion.go
  api/v1alpha4/gcpmachinetemplate_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/gcpmachine_types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/machine.go
  cloud/services/compute/instances/reconcile_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm, kind/api-change, ok-to-test

#684 docs: Add section about Machine Location
  docs/book/src/topics/machine-locations.md
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/M, approved, lgtm, ok-to-test

#788 add richardcase to capg maintainers
  OWNERS_ALIASES
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/XS, approved, lgtm

#786 Allow to use local-ssd disk type
  .gitignore
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  go.mod
  go.sum
Labels: kind/bug, release-note, cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#796 update CAPI to 1.3.1 and other cleanups
  .github/dependabot.yml
  Dockerfile
  Makefile
  Tiltfile
  clusterctl-settings.json
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm

#797 update CAPI to v1.2.8
  Dockerfile
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm
