Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2022-11, with the labels that each got.

#644 feat: Add support for feature gates
  feature/feature.go
  feature/gates.go
  go.mod
  main.go
Labels: release-note, cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#751 Fix compute service initialization in tests
  cloud/scope/cluster.go
  cloud/services/compute/instances/reconcile_test.go
  cloud/services/compute/subnets/reconcile_test.go
Labels: kind/bug, release-note, cncf-cla: yes, size/S, approved, lgtm

#750 Bump k8s version for envtest
  Makefile
Labels: release-note, cncf-cla: yes, size/XS, approved, lgtm

#765 update CAPI to v1.2.6 and golang to 1.18.8
  Dockerfile
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/M, approved, lgtm

#767 update CAPI to v1.2.6 and golang to 1.18.8
  Dockerfile
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm
