Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2022-01, with the labels that each got.

#479 Replace some occurences of ToNot(HaveOccurred())
  controllers/suite_test.go
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup, ok-to-test

#483 Bash script added for shellcheck verification
  Makefile
  hack/ensure-go.sh
  hack/ensure-kind.sh
  hack/kustomize-sub.sh
  hack/verify-shellcheck.sh
  hack/version.sh
  scripts/ci-build.sh
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
  scripts/ci-make.sh
  scripts/ci-test.sh
  scripts/kind-with-registry.sh
  scripts/setup-dev-enviroment.sh
  tilt_modules/cert_manager/test/test.sh
Labels: release-note, cncf-cla: yes, size/L, approved, lgtm

#481 Make cert manager install in makefile more resilient
  Makefile
  hack/install-cert-manager.sh
Labels: release-note, cncf-cla: yes, size/M, approved, lgtm

#488 Update README.md
  README.md
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/S, approved, lgtm, ok-to-test
