Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2022-08, with the labels that each got.

#671 Fix apidiff target
  Makefile
Labels: release-note, cncf-cla: yes, size/S, approved, lgtm, kind/cleanup

#672 Minor docs / Tiltfile cleanup
  Tiltfile
  docs/book/src/developers/development.md
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm, kind/cleanup, ok-to-test

#663 Upgrade golang to v1.18.3
  .github/workflows/lint.yml
  .golangci.yml
  Dockerfile
  Makefile
  Tiltfile
  docs/book/src/developers/development.md
  go.mod
  go.sum
  hack/ensure-go.sh
  hack/tools/go.mod
  hack/tools/go.sum
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, approved, lgtm

#675 Update cloudbuild to go 1.18
  cloudbuild.yaml
Labels: release-note, cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup

#678 Update CAPI to v1.2.0
  Dockerfile
  Makefile
  Tiltfile
  controllers/gcpcluster_controller.go
  go.mod
  go.sum
  metadata.yaml
  test/e2e/config/gcp-ci.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm

#680 docs: add IMAGE_ID export to prerequisites
  docs/book/src/topics/prerequisites.md
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/XS, approved, lgtm, ok-to-test

#690 update capi to v1.2.1
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/M, approved, lgtm

#662 Fix panic when no failure domain found
  cloud/scope/machine.go
Labels: kind/bug, release-note, cncf-cla: yes, size/XS, approved, lgtm

#685 Fix broken `TestGCPClusterTemplate_ValidateUpdate` test
  api/v1beta1/gcpclustertemplate_webhook_test.go
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm, kind/failing-test, ok-to-test

#689 Remove Hardcoded failureDomain in Template
  templates/cluster-template.yaml
Labels: kind/bug, release-note, cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#692 fix typo
  cloud/services/compute/instances/reconcile.go
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup

#693 Fix make target for test with coverage
  .gitignore
  Makefile
  scripts/ci-test-coverage.sh
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#699 feat: Upgrade Cert-Manager version to the latest(v1.9.1)
  hack/install-cert-manager.sh
Labels: kind/feature, release-note, cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#702 Bump golangci-lint to v1.49.0
  .github/workflows/lint.yml
  .golangci.yml
  Makefile
  main.go
Labels: release-note, cncf-cla: yes, size/S, approved, lgtm, kind/cleanup
