Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2022-06, with the labels that each got.

#614 Upgrade CAPI to 1.1.4 / Go to 1.17.11 and k8s images
  Dockerfile
  Makefile
  Tiltfile
  go.mod
  go.sum
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#584 Pick a zone for worker nodes automatically when a failureDomain is not specified in MachineDeployment
  cloud/scope/machine.go
  cloud/services/compute/instances/reconcile_test.go
  test/e2e/data/infrastructure-gcp/cluster-template-ci.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-md-remediation.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-prow-ci-version.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-topology.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-upgrades.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#617 bump golangci-lint version to v1.46.2
  .github/workflows/lint.yml
  Makefile
Labels: kind/feature, release-note, cncf-cla: yes, size/S, approved, lgtm

#623 Fix GitHub Actions for Links
  .github/workflows/link-check.yml
  .markdownlinkcheck.json
Labels: kind/bug, release-note-none, cncf-cla: yes, kind/documentation, size/S, approved, lgtm, ok-to-test

#613 Fix Typo to `prerequisites.md`
  docs/book/src/developers/releasing.md
  docs/book/src/topics/prerequisites.md
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/XS, approved, lgtm, ok-to-test

#616 Improve resilience of cluster delete
  cloud/scope/cluster.go
  cloud/services/compute/firewalls/reconcile.go
  cloud/services/compute/instances/reconcile.go
  cloud/services/compute/networks/reconcile.go
Labels: kind/bug, release-note-none, cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#624 update calico to use release v3.23
  test/e2e/data/cni/calico/calico.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm

#634 Add info about the kubernetes version env variable
  docs/book/src/developers/development.md
Labels: release-note, cncf-cla: yes, kind/documentation, size/XS, approved, lgtm, ok-to-test

#637 update KIND version to latest
  docs/book/src/developers/development.md
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/XS, approved, lgtm, ok-to-test
