Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2022-09, with the labels that each got.

#712 Remove slices of pointers to make conversion-gen happy
  api/v1alpha3/gcpcluster_conversion.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/gcpcluster_conversion.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/services/compute/subnets/reconcile_test.go
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#713 Allow to customize the subnet purpose
  api/v1alpha3/gcpcluster_conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/gcpcluster_conversion.go
  api/v1alpha4/gcpclustertemplate_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/cluster.go
  cloud/services/compute/subnets/reconcile_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#717 update capi to v1.1.6
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/M, approved, lgtm

#718 Marke EnableFlowLogs as optional
  api/v1beta1/types.go
Labels: kind/bug, release-note, cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#725 doc fixes
  CONTRIBUTING.md
  docs/book/src/developers/development.md
  docs/book/src/developers/releasing.md
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/S, approved, lgtm, ok-to-test

#724 Subnet role must be passed
  cloud/scope/cluster.go
Labels: kind/bug, release-note, cncf-cla: yes, size/XS, approved, lgtm, ok-to-test
