Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2023-03, with the labels that each got.

#862 Update GO to v1.19.7 and CAPI to v1.3.5
  Dockerfile
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/M, approved, lgtm

#868 Bump github.com/golangci/golangci-lint from 1.50.1 to 1.52.1
  Makefile
  exp/controllers/gcpmanagedcluster_controller.go
  hack/tools/tools.go
  scripts/go_install.sh
Labels: release-note, cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup

#869 Update calico v.3.25.0 for E2E testing
  test/e2e/data/cni/calico/calico.yaml
Labels: release-note-none, cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#863 Update URL for Calico's manifest in Makefile
  Makefile
Labels: release-note, cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#876 Bump Controller-gen & Envsubst
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedmachinepools.yaml
Labels: release-note, cncf-cla: yes, size/M, approved, lgtm, kind/cleanup, ok-to-test

#878 Fix clusterctl move command by updating ControlPlane initialized cond…
  cloud/services/container/clusters/reconcile.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  exp/api/v1beta1/gcpmanagedcontrolplane_types.go
Labels: kind/bug, release-note, cncf-cla: yes, size/S, approved, lgtm, ok-to-test
