Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2023-12, with the labels that each got.

#1085 Bump controller-gen patch version
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedmachinepools.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
Labels: kind/bug, release-note, cncf-cla: yes, size/S, approved, lgtm

#1088 Fix update node pool when nodeLocation is empty
  cloud/services/container/nodepools/reconcile.go
Labels: kind/bug, release-note-none, cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1089 Fix GKE reconciliation when the version is set in the machine pool
  cloud/scope/managedmachinepool.go
Labels: kind/bug, release-note-none, cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1098 Fix GKE update version check
  cloud/services/container/clusters/reconcile.go
Labels: kind/bug, release-note, cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1027 Pass required RangeName to compute.SubnetworkSecondaryRange
  cloud/scope/cluster.go
  cloud/scope/managedcluster.go
Labels: kind/bug, release-note, cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1026 Support more configurations for GCPManagedMachinePool
  cloud/scope/managedmachinepool.go
  cloud/scope/managedmachinepool_test.go
  cloud/scope/scope_suite_test.go
  cloud/services/container/clusters/reconcile.go
  cloud/services/container/nodepools/reconcile.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedmachinepools.yaml
  exp/api/v1beta1/gcpmanagedmachinepool_types.go
  exp/api/v1beta1/gcpmanagedmachinepool_webhook.go
  exp/api/v1beta1/gcpmanagedmachinepool_webhook_test.go
  exp/api/v1beta1/types.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  exp/controllers/gcpmanagedmachinepool_controller.go
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, approved, lgtm, ok-to-test

#1100 Fix GKE MachinePool replicas per region
  cloud/scope/managedmachinepool.go
  cloud/services/container/nodepools/reconcile.go
  cloud/services/shared/machinepool.go
Labels: kind/bug, release-note, cncf-cla: yes, size/S, approved, lgtm, ok-to-test
