Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2023-06, with the labels that each got.

#945 Update CAPI to v1.3.8
  Dockerfile
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note-none, cncf-cla: yes, size/M, approved, lgtm

#946 [release-1.3] update CAPI to v1.3.8 and go to 1.19.10
  Dockerfile
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note-none, cncf-cla: yes, size/M, approved, lgtm

#885 chore: improve apiserver loadbalancer healthcheck
  cloud/scope/cluster.go
Labels: kind/feature, release-note, cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#966 build-gce-ubuntu-1804 is deprecated update to build-gce-ubuntu-2004
  docs/book/src/developers/cluster-creation.md
  docs/book/src/topics/prerequisites.md
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
Labels: release-note, cncf-cla: yes, size/S, approved, lgtm, kind/cleanup
