Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2023-01, with the labels that each got.

#798 Added CAPG monthly office-hours details
  README.md
Labels: release-note, cncf-cla: yes, kind/documentation, size/XS, approved, lgtm

#801 Add proposal for managed Kubernetes in CAPG
  docs/proposals/20221123-managed-kubernetes-in-capg.md
Labels: release-note, cncf-cla: yes, kind/documentation, size/L, approved, lgtm, ok-to-test

#764 Add proposal and scaffolding for managed Kubernetes in CAPG
  .github/workflows/lint.yml
  .golangci.yml
  Makefile
  api/v1alpha3/gcpcluster_conversion.go
  api/v1alpha3/gcpmachine_conversion.go
  api/v1alpha3/gcpmachinetemplate_conversion.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedmachinepools.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  docs/proposals/20221123-managed-kubernetes-in-capg.md
  exp/PROJECT
  exp/README.md
  exp/api/v1beta1/gcpmanagedcluster_types.go
  exp/api/v1beta1/gcpmanagedcluster_webhook.go
  exp/api/v1beta1/gcpmanagedcontrolplane_types.go
  exp/api/v1beta1/gcpmanagedcontrolplane_webhook.go
  exp/api/v1beta1/gcpmanagedmachinepool_types.go
  exp/api/v1beta1/gcpmanagedmachinepool_webhook.go
  exp/api/v1beta1/groupversion_info.go
  exp/api/v1beta1/types.go
  exp/api/v1beta1/webhook_suite_test.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  exp/controllers/doc.go
  exp/controllers/gcpmanagedcluster_controller.go
  exp/controllers/gcpmanagedcontrolplane_controller.go
  exp/controllers/gcpmanagedmachinepool_controller.go
  exp/controllers/suite_test.go
  exp/doc.go
  exp/hack/boilerplate.go.txt
  go.mod
  go.sum
  test/e2e/capi_test.go
  test/e2e/common.go
  test/e2e/conformance_test.go
  test/e2e/e2e_test.go
  test/e2e/suite_test.go
Labels: size/XXL, release-note, cncf-cla: yes, kind/documentation, approved, lgtm, ok-to-test

#770 Implement the reconciliation loop for GCPManagedControlPlane (GKE Part 3)
  cloud/interfaces.go
  cloud/scope/credentials.go
  cloud/scope/managedcluster.go
  cloud/scope/managedcontrolplane.go
  cloud/services/container/clusters/doc.go
  cloud/services/container/clusters/kubeconfig.go
  cloud/services/container/clusters/reconcile.go
  cloud/services/container/clusters/service.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  exp/api/v1beta1/conditions_consts.go
  exp/api/v1beta1/gcpmanagedcontrolplane_types.go
  exp/api/v1beta1/gcpmanagedcontrolplane_webhook.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  exp/controllers/gcpmanagedcluster_controller.go
  exp/controllers/gcpmanagedcontrolplane_controller.go
  go.mod
  go.sum
  main.go
  util/hash/base36.go
  util/reconciler/defaults.go
Labels: size/XXL, release-note, cncf-cla: yes, approved, lgtm, ok-to-test

#809 Add support for confidential compute
  api/v1alpha3/gcpmachine_conversion.go
  api/v1alpha3/gcpmachinetemplate_conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/gcpmachine_conversion.go
  api/v1alpha4/gcpmachinetemplate_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/gcpmachine_types.go
  api/v1beta1/gcpmachine_webhook.go
  api/v1beta1/gcpmachine_webhook_test.go
  api/v1beta1/gcpmachinetemplate_webhook.go
  api/v1beta1/gcpmachinetemplate_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/machine.go
  cloud/services/compute/instances/reconcile.go
  cloud/services/compute/instances/reconcile_test.go
  cloud/services/compute/instances/service.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
  go.mod
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, approved, lgtm, ok-to-test

#815 update cert-manager to 1.11.0 release and use python3
  Tiltfile
  docs/book/src/developers/development.md
  hack/boilerplate/boilerplate.py.txt
  hack/boilerplate/boilerplate_test.py
  hack/boilerplate/test/fail.py
  hack/boilerplate/test/pass.py
  hack/checkin_account.py
  hack/checkout_account.py
  hack/heartbeat_account.py
  hack/install-cert-manager.sh
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
Labels: kind/feature, release-note, cncf-cla: yes, size/M, approved, lgtm

#816 [release-1.1] use python3, python2 is deprecated
  docs/book/src/developers/development.md
  hack/boilerplate/boilerplate.py.txt
  hack/boilerplate/boilerplate_test.py
  hack/boilerplate/test/fail.py
  hack/boilerplate/test/pass.py
  hack/checkin_account.py
  hack/checkout_account.py
  hack/heartbeat_account.py
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
Labels: release-note, cncf-cla: yes, size/M, approved, lgtm, kind/cleanup

#817 [release-1.2] use python3, python2 is deprecated
  docs/book/src/developers/development.md
  hack/boilerplate/boilerplate.py.txt
  hack/boilerplate/boilerplate_test.py
  hack/boilerplate/test/fail.py
  hack/boilerplate/test/pass.py
  hack/checkin_account.py
  hack/checkout_account.py
  hack/heartbeat_account.py
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
Labels: release-note, cncf-cla: yes, size/M, approved, lgtm, kind/cleanup
