Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2023-02, with the labels that each got.

#789 Implement the reconciliation loop for GCPManagedMachinePool (GKE Part 4)
  cloud/scope/managedcontrolplane.go
  cloud/scope/managedmachinepool.go
  cloud/services/container/clusters/kubeconfig.go
  cloud/services/container/clusters/reconcile.go
  cloud/services/container/nodepools/doc.go
  cloud/services/container/nodepools/reconcile.go
  cloud/services/container/nodepools/service.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedmachinepools.yaml
  config/rbac/role.yaml
  exp/api/v1beta1/conditions_consts.go
  exp/api/v1beta1/gcpmanagedcluster_types.go
  exp/api/v1beta1/gcpmanagedmachinepool_types.go
  exp/api/v1beta1/types.go
  exp/api/v1beta1/webhook_suite_test.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  exp/controllers/gcpmanagedcontrolplane_controller.go
  exp/controllers/gcpmanagedmachinepool_controller.go
  go.mod
  main.go
  util/location/location.go
  util/resourceurl/parse.go
Labels: size/XXL, release-note, cncf-cla: yes, approved, lgtm, ok-to-test

#802 Add feature flag and enable controllers (GKE part 5)
  cloud/scope/clients.go
  cloud/scope/cluster.go
  cloud/scope/credentials.go
  cloud/scope/managedcluster.go
  cloud/scope/managedcontrolplane.go
  cloud/scope/managedmachinepool.go
  config/manager/manager.yaml
  exp/api/v1beta1/gcpmanagedcontrolplane_webhook.go
  exp/controllers/gcpmanagedcluster_controller.go
  exp/controllers/gcpmanagedcontrolplane_controller.go
  exp/controllers/gcpmanagedmachinepool_controller.go
  feature/feature.go
  main.go
  templates/cluster-template-gke.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm

#835 Rename k8s.gcr.io to registry.k8s.io and go updates
  Dockerfile
  Makefile
  test/e2e/data/infrastructure-gcp/cluster-template-prow-ci-version.yaml
Labels: release-note, cncf-cla: yes, size/S, approved, lgtm, kind/cleanup

#834 Add docs (GKE part 8)
  docs/book/src/topics/gke/cluster-upgrades.md
  docs/book/src/topics/gke/creating-a-cluster.md
  docs/book/src/topics/gke/disabling.md
  docs/book/src/topics/gke/enabling.md
  docs/book/src/topics/gke/index.md
Labels: release-note, cncf-cla: yes, kind/documentation, size/M, approved, lgtm, needs-ok-to-test

#833 Add validation webhooks (GKE part 7)
  exp/api/v1beta1/gcpmanagedcluster_webhook.go
  exp/api/v1beta1/gcpmanagedcontrolplane_webhook.go
  exp/api/v1beta1/gcpmanagedmachinepool_webhook.go
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#845 Return correct error variable
  cloud/services/container/clusters/kubeconfig.go
Labels: kind/bug, release-note-none, cncf-cla: yes, size/XS, approved, lgtm
