Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2024-02, with the labels that each got.

#1115 chore: bump CAPI to v1.6.x
  .github/workflows/lint.yml
  Dockerfile
  Makefile
  Tiltfile
  api/v1alpha3/doc.go
  api/v1alpha3/gcpcluster_conversion.go
  api/v1alpha3/gcpcluster_types.go
  api/v1alpha3/gcpmachine_conversion.go
  api/v1alpha3/gcpmachine_types.go
  api/v1alpha3/gcpmachinetemplate_conversion.go
  api/v1alpha3/gcpmachinetemplate_types.go
  api/v1alpha3/groupversion_info.go
  api/v1alpha3/labels.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/cluster.go
  cloud/scope/machine.go
  cloud/scope/managedcluster.go
  cloud/scope/managedmachinepool.go
  cloud/scope/providerid.go
  cloud/services/compute/instances/reconcile.go
  cloud/services/compute/instances/reconcile_test.go
  cloud/services/compute/loadbalancers/reconcile.go
  cloud/services/compute/networks/reconcile.go
  cloud/services/compute/subnets/reconcile_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedmachinepools.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/suite_test.go
  docs/book/src/developers/cluster-creation.md
  exp/api/v1beta1/webhook_suite_test.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
  test/e2e/capi_test.go
  test/e2e/config/gcp-ci.yaml
  test/e2e/conformance_test.go
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/e2e_gke_test.go
  test/e2e/e2e_test.go
Labels: size/XXL, release-note, cncf-cla: yes, approved, lgtm, ok-to-test

#1099 Fix node pool update when MachinePool version is set
  cloud/services/container/nodepools/reconcile.go
  exp/api/v1beta1/types.go
Labels: kind/bug, release-note, cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#1104 Fix GKE autoscaling conditions in reconciliation process
  cloud/services/container/nodepools/reconcile.go
  exp/api/v1beta1/types.go
  tilt-provider.json
Labels: kind/bug, release-note, cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#1120 ⚠️ Remove v1alpha4 API types
  Makefile
  api/v1alpha4/conversion_test.go
  api/v1alpha4/doc.go
  api/v1alpha4/gcpcluster_conversion.go
  api/v1alpha4/gcpcluster_types.go
  api/v1alpha4/gcpclustertemplate_conversion.go
  api/v1alpha4/gcpclustertemplate_types.go
  api/v1alpha4/gcpmachine_conversion.go
  api/v1alpha4/gcpmachine_types.go
  api/v1alpha4/gcpmachinetemplate_conversion.go
  api/v1alpha4/gcpmachinetemplate_types.go
  api/v1alpha4/groupversion_info.go
  api/v1alpha4/labels.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
  main.go
Labels: size/XXL, release-note, cncf-cla: yes, needs-rebase, approved, lgtm, kind/api-change

#1131 docs: basic netlify configuration for book
  docs/book/Makefile
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  netlify.toml
Labels: release-note, cncf-cla: yes, kind/documentation, size/L, approved, lgtm, ok-to-test

#1135 Create CAPG book from existing docs
  docs/book/book.toml
  docs/book/src/SUMMARY.md
  docs/book/src/developers/index.md
  docs/book/src/getting-started.md
  docs/book/src/introduction.md
  docs/book/src/topics/index.md
  docs/book/theme/css/general.css
  docs/book/theme/favicon.png
  docs/book/theme/head.hbs
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, approved, lgtm, ok-to-test

#1150 📖 docs: link to book from readme
  README.md
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/XS, approved, lgtm, ok-to-test

#1155 update golang to 1.21.7 in dockerfile and other updates
  Dockerfile
  metadata.yaml
  scripts/ci-e2e.sh
  test/e2e/capi_test.go
  test/e2e/config/gcp-ci.yaml
Labels: release-note, cncf-cla: yes, size/M, approved, lgtm

#1157 update CAPI to 1.6.2
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/gcp-ci.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/M, approved, lgtm, kind/cleanup

#1137 Add support for disk encryption key in GCPMachine
  api/v1beta1/gcpmachine_types.go
  api/v1beta1/gcpmachine_webhook.go
  api/v1beta1/gcpmachine_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/machine.go
  cloud/services/compute/instances/reconcile_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
Labels: release-note, cncf-cla: yes, size/XL, approved, lgtm, ok-to-test
