Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2024-03, with the labels that each got.

#1158 fix: invalid string for manager's deployment containerPort
  config/manager/manager.yaml
Labels: kind/bug, release-note, cncf-cla: yes, size/XS, approved, lgtm

#1164 README: update CAPG meeting time
  README.md
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/XS, approved, lgtm

#1166 hack: improve boskos scripts logging
  hack/checkin_account.py
  hack/checkout_account.py
  hack/heartbeat_account.py
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm

#1190 fix: The subject was incorrectly used in some parts of the document.
  docs/proposals/20221123-managed-kubernetes-in-capg.md
Labels: release-note, cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#961 Fix Cluster Creation in User Provided Subnet
  cloud/services/compute/subnets/reconcile.go
  cloud/services/container/clusters/reconcile.go
  exp/api/v1beta1/gcpmanagedcluster_webhook.go
  test/e2e/config/gcp-ci.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-ci-gke-custom-subnet.yaml
  test/e2e/e2e_gke_test.go
Labels: kind/bug, release-note, cncf-cla: yes, size/L, approved, lgtm, ok-to-test
