Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2024-11, with the labels that each got.

#1351 chore: add clusterclass sample template
  templates/cluster-template-clusterclass.yaml
  templates/cluster-template-topology.yaml
Labels: kind/feature, release-note-none, cncf-cla: yes, size/L, approved, lgtm

#1353 Improve book structure and add clusterclass examples
  docs/book/src/SUMMARY.md
  docs/book/src/clusterclass/disabling.md
  docs/book/src/clusterclass/enabling.md
  docs/book/src/clusterclass/index.md
  docs/book/src/clusterclass/provision.md
  docs/book/src/getting-started.md
  docs/book/src/managed/disabling.md
  docs/book/src/managed/enabling.md
  docs/book/src/managed/index.md
  docs/book/src/managed/provision.md
  docs/book/src/managed/upgrades.md
  docs/book/src/prerequisites.md
  docs/book/src/quick-start.md
  docs/book/src/self-managed/cni.md
  docs/book/src/self-managed/index.md
  docs/book/src/self-managed/provision.md
  docs/book/src/topics/gke/creating-a-cluster.md
  docs/book/src/topics/index.md
Labels: release-note, cncf-cla: yes, kind/documentation, size/L, approved, lgtm

#1356 [PROPOSAL] Add salasberryfin as reviewer
  OWNERS_ALIASES
Labels: kind/feature, release-note, cncf-cla: yes, size/XS, approved, lgtm

#1358 Fix broken book links and add section on adding new E2E tests
  docs/book/src/SUMMARY.md
  docs/book/src/developers/e2e.md
  docs/book/src/managed/index.md
Labels: release-note-none, cncf-cla: yes, size/M, approved, lgtm, kind/cleanup

#1364 fix: wrap error when nodepool update/delete fails
  cloud/services/container/nodepools/reconcile.go
  exp/controllers/gcpmanagedmachinepool_controller.go
Labels: kind/bug, release-note, cncf-cla: yes, size/S, approved, lgtm

#1366 feat: add support for identity service in GCPManagedControlPlane
  cloud/services/container/clusters/reconcile.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  exp/api/v1beta1/gcpmanagedcontrolplane_types.go
Labels: kind/feature, release-note, cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#1367 chore: support registry and tag overrides in makefile
  Makefile
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup
