Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2024-04, with the labels that each got.

#1204 CI and Go updates
  .github/dependabot.yml
  .github/workflows/codespell.yml
  .github/workflows/cover.yaml
  .github/workflows/link-check.yml
  .github/workflows/lint.yml
  .github/workflows/pr-gh-workflow-approve.yaml
  Dockerfile
  Makefile
  hack/tools/go.mod
  netlify.toml
Labels: release-note, cncf-cla: yes, size/M, approved, lgtm, kind/cleanup

#1193 Bump CAPI to v1.7.0
  Makefile
  Tiltfile
  cloud/providerid/providerid_test.go
  cloud/services/compute/instances/reconcile_test.go
  cloud/services/compute/subnets/reconcile_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedmachinepools.yaml
  exp/controllers/gcpmanagedmachinepool_controller.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  metadata.yaml
  test/e2e/config/gcp-ci.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: kind/feature, size/XXL, release-note, cncf-cla: yes, approved, lgtm

#1209 Also bump CAPI quickstart to v1.7.0
  Makefile
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup

#1210 Bump cert-manager to v1.14.4 to align with CAPI
  Makefile
  Tiltfile
  hack/install-cert-manager.sh
Labels: kind/support, release-note, cncf-cla: yes, size/S, approved, lgtm

#1211 fix lint job
  .github/workflows/lint.yml
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm

#1207 Allow configuration of API server instance group name
  api/v1beta1/gcpcluster_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/interfaces.go
  cloud/scope/cluster.go
  cloud/scope/machine.go
  cloud/scope/managedcluster.go
  cloud/services/compute/loadbalancers/reconcile_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclusters.yaml
  exp/api/v1beta1/gcpmanagedcluster_types.go
  exp/api/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1217 fix: Makefile: nightly build add bucket
  Makefile
Labels: kind/support, release-note-none, cncf-cla: yes, size/XS, approved, lgtm
