Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2024-05, with the labels that each got.

#1234 Update CAPI / golangci-lint / go
  .github/workflows/codespell.yml
  .github/workflows/lint.yml
  .golangci.yml
  Dockerfile
  Makefile
  Tiltfile
  api/v1beta1/gcpcluster_webhook.go
  api/v1beta1/gcpclustertemplate_webhook_test.go
  api/v1beta1/gcpmachine_webhook.go
  api/v1beta1/gcpmachinetemplate_webhook_test.go
  api/v1beta1/types.go
  cloud/scope/clients.go
  cloud/scope/cluster.go
  cloud/scope/machine.go
  cloud/scope/managedcluster.go
  cloud/scope/managedmachinepool_test.go
  cloud/services/compute/loadbalancers/reconcile_test.go
  cloud/services/container/clusters/errors.go
  cloud/services/container/clusters/kubeconfig.go
  cloud/services/container/clusters/reconcile.go
  cloud/services/container/nodepools/reconcile.go
  cloud/services/shared/tags.go
  exp/api/v1beta1/gcpmanagedcluster_webhook.go
  exp/api/v1beta1/gcpmanagedmachinepool_webhook.go
  exp/api/v1beta1/gcpmanagedmachinepool_webhook_test.go
  exp/api/v1beta1/webhook_suite_test.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  netlify.toml
  test/e2e/capi_test.go
  test/e2e/config/gcp-ci.yaml
  test/e2e/conformance_test.go
  test/e2e/e2e_gke_test.go
  test/e2e/e2e_test.go
  test/e2e/suite_test.go
Labels: release-note, cncf-cla: yes, size/XL, approved, lgtm, kind/cleanup

#1236 update k8s dependencies
  go.mod
  go.sum
Labels: release-note, cncf-cla: yes, size/M, approved, lgtm, kind/cleanup

#1235 Update CAPI / go / dependencies for release-1.6
  .github/workflows/lint.yml
  Dockerfile
  Makefile
  Tiltfile
  cloud/providerid/providerid_test.go
  cloud/services/compute/firewalls/service.go
  cloud/services/compute/instances/reconcile_test.go
  cloud/services/compute/instances/service.go
  cloud/services/compute/loadbalancers/reconcile.go
  cloud/services/compute/loadbalancers/service.go
  cloud/services/compute/networks/service.go
  cloud/services/compute/subnets/reconcile_test.go
  cloud/services/compute/subnets/service.go
  exp/controllers/gcpmanagedmachinepool_controller.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  netlify.toml
  test/e2e/config/gcp-ci.yaml
Labels: release-note, cncf-cla: yes, size/L, approved, lgtm, kind/cleanup

#1243 Add documentation for nightly builds
  docs/book/src/SUMMARY.md
  docs/book/src/developers/nightlies.md
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/M, approved, lgtm

#1222 Create an Internal Load Balancer if configured
  api/v1beta1/gcpcluster_webhook.go
  api/v1beta1/labels.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/cluster.go
  cloud/services/compute/loadbalancers/reconcile.go
  cloud/services/compute/loadbalancers/reconcile_test.go
  cloud/services/compute/loadbalancers/service.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclusters.yaml
  controllers/gcpcluster_controller.go
Labels: kind/feature, size/XXL, release-note, cncf-cla: yes, approved, lgtm, ok-to-test

#1247 Typofix in prerequisites.md
  docs/book/src/topics/prerequisites.md
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/XS, approved, lgtm, ok-to-test

#1248 Bump setup-envtest to use new controller-tools binaries
  Makefile
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup
