Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2024-06, with the labels that each got.

#1245 Add e2e test for internal load balancer
  test/e2e/config/gcp-ci.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-ci-with-internal-lb.yaml
  test/e2e/e2e_test.go
Labels: kind/feature, release-note-none, cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1253 [release-1.6] Bump setup-envtest to use new controller-tools binaries
  Makefile
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup

#1254 Use reference for Internal LB address
  cloud/services/compute/loadbalancers/reconcile.go
Labels: kind/bug, release-note-none, cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1267 Bump CAPI to v1.7.3
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/gcp-ci.yaml
Labels: release-note, cncf-cla: yes, size/M, approved, lgtm

#1269 drop failing and not in use job
  .github/workflows/cover.yaml
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm, kind/cleanup

#1186 Support additional GCPManagedControlPlane fields
  cloud/services/container/clusters/reconcile.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  exp/api/v1beta1/gcpmanagedcontrolplane_types.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  hack/tools/go.mod
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1275 Set Labels on Disks and ForwardingRules resources
  cloud/scope/cluster.go
  cloud/scope/machine.go
  cloud/services/compute/instances/reconcile_test.go
  cloud/services/compute/loadbalancers/reconcile_test.go
Labels: kind/bug, release-note, cncf-cla: yes, size/M, approved, lgtm, ok-to-test
