Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2024-10, with the labels that each got.

#1318 Bump CAPI to v1.8
  .github/workflows/lint.yml
  .golangci.yml
  Dockerfile
  Makefile
  api/v1beta1/gcpcluster_webhook_test.go
  api/v1beta1/gcpclustertemplate_webhook_test.go
  api/v1beta1/gcpmachine_webhook_test.go
  api/v1beta1/gcpmachinetemplate_webhook_test.go
  cloud/scope/managedcontrolplane.go
  cloud/scope/managedmachinepool.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedmachinepools.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/gcpcluster_controller.go
  controllers/gcpmachine_controller.go
  controllers/suite_test.go
  exp/api/v1beta1/gcpmanagedmachinepool_webhook.go
  exp/api/v1beta1/webhook_suite_test.go
  exp/controllers/gcpmanagedcluster_controller.go
  exp/controllers/gcpmanagedcontrolplane_controller.go
  exp/controllers/gcpmanagedmachinepool_controller.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
  metadata.yaml
  test/e2e/config/gcp-ci.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/gke.go
  util/reconciler/defaults_test.go
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, approved, lgtm

#1313 Add support for Spot VMs
  api/v1beta1/gcpmachine_types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/machine.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
  docs/book/src/topics/preemptible-vms.md
Labels: kind/feature, release-note, cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#1335 chore: update sig-cluster-lifecycle links
  CONTRIBUTING.md
  README.md
Labels: release-note-none, cncf-cla: yes, kind/documentation, size/XS, approved, lgtm

#1339 Increase test coverage for managed cluster webhooks
  exp/api/v1beta1/gcpmanagedcluster_webhook_test.go
  exp/api/v1beta1/gcpmanagedcontrolplane_webhook_test.go
  exp/api/v1beta1/gcpmanagedmachinepool_webhook_test.go
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, approved, lgtm

#1333 Support Kubernetes 1.29+
  templates/cluster-template.yaml
Labels: kind/bug, release-note, cncf-cla: yes, size/XS, approved, lgtm

#1349 update gh permissions
  .github/workflows/codespell.yml
  .github/workflows/link-check.yml
  .github/workflows/lint.yml
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm, kind/cleanup
