Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2024-01, with the labels that each got.

#1108 Add linuxNodeConfig field to GCPManagedMachinePool
  cloud/scope/managedmachinepool.go
  cloud/services/container/nodepools/reconcile.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedmachinepools.yaml
  exp/api/v1beta1/gcpmanagedmachinepool_types.go
  exp/api/v1beta1/types.go
  exp/api/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1119 main: logged correct error in branch
  main.go
Labels: kind/bug, release-note-none, cncf-cla: yes, size/XS, approved, lgtm

#1105 Strip the patch number in GKE master version
  cloud/services/container/clusters/reconcile.go
Labels: kind/bug, release-note, cncf-cla: yes, size/S, approved, lgtm, ok-to-test
