Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2025-04, with the labels that each got.

#1461 cloudbuild: bump gcb image to get go 1.23
  cloudbuild-nightly.yaml
  cloudbuild.yaml
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm

#1449 Dependency updates and update Go
  .github/dependabot.yml
  .github/workflows/lint.yml
  Dockerfile
  go.mod
  go.sum
Labels: release-note-none, cncf-cla: yes, size/L, approved, lgtm

#1458 fix: make sure machine pools are deleted before gke cluster
  exp/controllers/gcpmanagedcluster_controller.go
Labels: kind/bug, release-note, cncf-cla: yes, size/M, approved, lgtm
