Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2025-09, with the labels that each got.

#1523 chore: update README with correct office hours time
  README.md
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm

#1527 tests: test with kubernetes 1.33.2
  test/e2e/config/gcp-ci.yaml
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm

#1514 Replace context.Background() with t.Context()
  api/v1beta1/gcpcluster_webhook_test.go
  api/v1beta1/gcpclustertemplate_webhook_test.go
  api/v1beta1/gcpmachine_webhook_test.go
  api/v1beta1/gcpmachinetemplate_webhook_test.go
  exp/api/v1beta1/gcpmanagedcluster_webhook_test.go
  exp/api/v1beta1/gcpmanagedcontrolplane_webhook_test.go
  exp/api/v1beta1/gcpmanagedmachinepool_webhook_test.go
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#1535 chore: refactor service account into a standalone function
  cloud/scope/machine.go
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm

#1531 Provide a MinPortsPerVM for Nat Router
  api/v1beta1/types.go
  cloud/scope/cluster.go
  cloud/scope/managedcluster.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclustertemplates.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/M, approved, lgtm, ok-to-test
