Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2025-03, with the labels that each got.

#1434 feat: align GCPManagedControlPlane with CAPI >=v1.9
  .golangci.yml
  cloud/scope/managedcontrolplane.go
  cloud/services/container/clusters/reconcile.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  exp/api/v1beta1/gcpmanagedcontrolplane_types.go
  exp/api/v1beta1/gcpmanagedcontrolplane_webhook.go
  exp/api/v1beta1/gcpmanagedcontrolplane_webhook_test.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  test/e2e/data/infrastructure-gcp/cluster-template-ci-gke.yaml
Labels: kind/bug, cncf-cla: yes, size/L, approved, lgtm, release-note-action-required

#1444 fix: panic on gke cluster creation
  cloud/services/container/clusters/reconcile.go
Labels: kind/bug, release-note-none, cncf-cla: yes, size/S, approved, lgtm

#1446 chore: update tiltfile for immutable images
  Tiltfile
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm

#1455 fix: panic on gke cluster deletion
  exp/controllers/gcpmanagedcontrolplane_controller.go
Labels: kind/bug, release-note, cncf-cla: yes, size/XS, approved, lgtm
