Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2025-01, with the labels that each got.

#1292 feat: support setting loggingService and monitoringService
  cloud/services/container/clusters/reconcile.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  exp/api/v1beta1/gcpmanagedcontrolplane_types.go
  exp/api/v1beta1/gcpmanagedcontrolplane_webhook.go
  exp/api/v1beta1/zz_generated.deepcopy.go
Labels: release-note, cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1404 Cleanup golangci-lint and bump go in dockerfile
  .github/workflows/lint.yml
  Dockerfile
Labels: release-note, cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup

#1357 Bump CAPI to v1.9.z
  Makefile
  api/v1beta1/gcpmachine_types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/interfaces.go
  cloud/scope/machine.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedmachinepools.yaml
  controllers/gcpcluster_controller.go
  controllers/gcpmachine_controller.go
  exp/controllers/gcpmanagedcluster_controller.go
  exp/controllers/gcpmanagedcontrolplane_controller.go
  exp/controllers/gcpmanagedmachinepool_controller.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  metadata.yaml
  test/e2e/config/gcp-ci.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, approved, lgtm

#1406 chore: bump golang to 1.23.5
  .github/workflows/lint.yml
  Dockerfile
  Makefile
  go.mod
  hack/tools/go.mod
  netlify.toml
Labels: release-note, cncf-cla: yes, size/S, approved, lgtm

#1413 Revert "chore: bump golang to 1.23.5"
  .github/workflows/lint.yml
  Dockerfile
  Makefile
  go.mod
  hack/tools/go.mod
  netlify.toml
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm

#1409 CORS-3841: Add custom Endpoints to CAPG
  api/v1beta1/endpoints.go
  api/v1beta1/gcpcluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/clients.go
  cloud/scope/cluster.go
  cloud/scope/managedcluster.go
  cloud/scope/managedcontrolplane.go
  cloud/scope/managedmachinepool.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclusters.yaml
  exp/api/v1beta1/gcpmanagedcluster_types.go
  exp/api/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm, kind/api-change, ok-to-test

#1416 chore: cherry pick dependabot bumps and fix linting issues
  cloud/services/container/clusters/reconcile.go
  go.mod
  go.sum
Labels: release-note-none, cncf-cla: yes, size/L, approved, lgtm, kind/cleanup, tide/merge-method-squash

#1355 test: e2e cover clusterclass provisioning
  test/e2e/config/gcp-ci.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-topology.yaml
  test/e2e/data/infrastructure-gcp/withclusterclass/cluster-template-ci-topology.yaml
  test/e2e/e2e_test.go
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm
