Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2025-08, with the labels that each got.

#1371 fix: add IgnoreUnexported to Node Taints comparison
  cloud/services/container/nodepools/reconcile.go
  test/e2e/config/gcp-ci.yaml
  test/e2e/data/infrastructure-gcp/cluster-template-ci-gke.yaml
  test/e2e/e2e_gke_test.go
Labels: kind/bug, release-note, cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#1498 feat: add support for extended release channel
  cloud/services/container/clusters/reconcile.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanetemplates.yaml
  exp/api/v1beta1/gcpmanagedcontrolplane_types.go
Labels: release-note, cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#1510 chore: cleanup golangci-lint in Makefile
  Makefile
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm

#1511 update golangci-lint to v2.4
  .github/workflows/lint.yml
  Makefile
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup

#1500 chore: add Metadata kind to metadata
  metadata.yaml
Labels: release-note-none, cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup

#1504 feat: add fields to support workload identity & binary authorization
  cloud/services/container/clusters/reconcile.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanetemplates.yaml
  exp/api/v1beta1/gcpmanagedcontrolplane_types.go
  exp/api/v1beta1/types_class.go
  exp/api/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm

#1516 chore: don't use Requeue in controller-runtime
  controllers/gcpcluster_controller_test.go
  controllers/gcpmachine_controller.go
  controllers/gcpmachine_controller_test.go
  exp/controllers/gcpmanagedcontrolplane_controller.go
  exp/controllers/gcpmanagedmachinepool_controller.go
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm

#1517 chore: fix go vet errors around conditions.MarkFalse
  cloud/services/container/clusters/reconcile.go
  cloud/services/container/nodepools/reconcile.go
Labels: release-note, cncf-cla: yes, size/S, approved, lgtm
