Repository kubernetes-sigs/cluster-api-provider-gcp, pull requests merged in 2025-02, with the labels that each got.

#1410 Support SEV_SNP instance type configuration
  api/v1beta1/gcpmachine_types.go
  api/v1beta1/gcpmachine_webhook.go
  api/v1beta1/gcpmachine_webhook_test.go
  api/v1beta1/gcpmachinetemplate_webhook_test.go
  cloud/scope/machine.go
  cloud/services/compute/instances/reconcile_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
Labels: kind/feature, release-note, cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#1432 confidentialCompute: Fix "Encryted" typo
  api/v1beta1/gcpmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
Labels: kind/bug, release-note-none, cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#1435 go.mod drop unneded replaces
  go.mod
Labels: release-note-none, cncf-cla: yes, size/S, approved, lgtm, kind/cleanup
